const path = {
  // URL_API: "http://localhost:3300/api",
  URL_API: "https://react-booking-hotel-server.onrender.com/api",
  URL: "https://anhoct-hotel-admin.netlify.app",
  LOGIN: "login",
  DASHBOARD: "dashboard",
  ACCOUNT: "dashboard/account",
  ACCOUNT_UPDATE: "dashboard/account/update",
  HOADON: "dashboard/hoadon",
  CHITIETHD: "dashboard/chitiethd",
  DICHVU: "dashboard/dichvu",
  DICHVU_CREATE: "dashboard/dichvu/create",
  DICHVU_UPDATE: "dashboard/dichvu/update",
  LOAIPHONG: "dashboard/loaiphong",
  LOAIPHONG_CREATE: "dashboard/loaiphong/create",
  LOAIPHONG_UPDATE: "dashboard/loaiphong/update",
  PHONG: "dashboard/phong",
  PHONG_CREATE: "dashboard/phong/create",
  PHONG_UPDATE: "dashboard/phong/update",
  DATPHONG: "dashboard/datphong",
  DATPHONG_CREATE: "dashboard/datphong/create",
  DATPHONG_UPDATE: "dashboard/datphong/update",
};

export default path;
